local markdown = {
  markdownBlockquote = { fg = C.base0 },
  markdownBold = { fg = C.yellow, style = 'bold' },
  markdownCode = { fg = C.green },
  markdownCodeBlock = { fg = C.green },
  markdownCodeDelimiter = { fg = C.green },
  markdownH1 = { fg = C.blue },
  markdownH2 = { fg = C.blue },
  markdownH3 = { fg = C.blue },
  markdownH4 = { fg = C.blue },
  markdownH5 = { fg = C.blue },
  markdownH6 = { fg = C.blue },
  markdownHeadingDelimiter = { fg = C.blue },
  markdownHeadingRule = { fg = C.base0 },
  markdownId = { fg = C.violet },
  markdownIdDeclaration = { fg = C.blue },
  markdownIdDelimiter = { fg = C.base0 },
  markdownLinkDelimiter = { fg = C.base0 },
  markdownItalic = { style = 'italic' },
  markdownLinkText = { fg = C.blue },
  markdownListMarker = { fg = C.red },
  markdownOrderedListMarker = { fg = C.red },
  markdownRule = { fg = C.base0 },
  markdownUrl = { fg = C.cyan, style = 'underline' },
}

return markdown
