local markdown = {
		markdownBlockquote = {fg = C.green, },
		markdownCode = {fg = C.orange, },
		markdownCodeBlock = {fg = C.orange, },
		markdownCodeDelimiter = {fg = C.orange, },
		markdownH1 = {fg = C.vivid_blue, },
		markdownH2 = {fg = C.vivid_blue, },
		markdownH3 = {fg = C.vivid_blue, },
		markdownH4 = {fg = C.vivid_blue, },
		markdownH5 = {fg = C.vivid_blue, },
		markdownH6 = {fg = C.vivid_blue, },
		markdownHeadingDelimiter = {fg = C.vivid_blue, },
		markdownHeadingRule = {fg = C.fg, style = "bold", },
		markdownId = {fg = C.purple, },
		markdownIdDeclaration = {fg = C.blue, },
		markdownIdDelimiter = {fg = C.light_gray, },
		markdownLinkDelimiter = {fg = C.light_gray, },
		markdownBold = {fg = C.blue, style = "bold", },
		markdownItalic = {style = "italic", },
		markdownBoldItalic = {fg = C.yellow_orange, style = "bold,italic", },
		markdownListMarker = {fg = C.blue, },
		markdownOrderedListMarker = {fg = C.blue, },
		markdownRule = {fg = C.accent, },
		markdownUrl = {fg = C.cyan, style = "underline", },
		markdownLinkText = {fg = C.blue, },
		markdownFootnote = {fg = C.orange, },
		markdownFootnoteDefinition = {fg = C.orange, },
		markdownEscape = {fg = C.yellow_orange, },
}

return markdown