local Treesitter = {
  TSComment = { fg = C.base0 },
  TSAnnotation = { fg = C.blue },
  TSAttribute = { fg = C.cyan },
  TSConstructor = { fg = C.red },
  TSType = { fg = C.yellow },
  TSTypeBuiltin = { fg = C.yellow },
  TSConditional = { fg = C.green },
  TSException = { fg = C.green },
  TSInclude = { fg = C.orange },
  TSKeyword = { fg = C.green },
  TSKeywordReturn = { fg = C.green },
  TSKeywordFunction = { fg = C.green },
  TSLabel = { fg = C.green },
  TSNone = { fg = C.base1 },
  TSNamespace = { fg = C.green },
  TSRepeat = { fg = C.green },
  TSConstant = { fg = C.blue },
  TSConstBuiltin = { fg = C.cyan },
  TSFloat = { fg = C.cyan },
  TSNumber = { fg = C.cyan },
  TSBoolean = { fg = C.cyan },
  TSCharacter = { fg = C.green },
  TSError = { fg = C.red },
  TSFunction = { fg = C.blue },
  TSFuncBuiltin = { fg = C.blue },
  TSMethod = { fg = C.blue },
  TSConstMacro = { fg = C.cyan },
  TSFuncMacro = { fg = C.blue },
  TSProperty = { fg = C.blue },
  TSOperator = { fg = C.green },
  TSField = { fg = C.blue },
  TSParameter = { fg = C.blue },
  TSParameterReference = { fg = C.red },
  TSVariable = { fg = C.base1 },
  TSVariableBuiltin = { fg = C.red },
  TSSymbol = { fg = C.cyan },
  TSText = { fg = C.base1 },
  TSTextReference = { fg = C.red },
  TSPunctDelimiter = { fg = C.red },
  TSTagDelimiter = { fg = C.red },
  TSTagAttribute = { fg = C.blue },
  TSPunctBracket = { fg = C.red },
  TSPunctSpecial = { fg = C.red },
  TSString = { fg = C.cyan },
  TSStringRegex = { fg = C.orange },
  TSStringEscape = { fg = C.orange },
  TSTag = { fg = C.green },
  TSEmphasis = { style = 'italic' },
  TSUnderline = { style = 'underline' },
  TSNote = { fg = C.yellow, style = 'bold' },
  TSWarning = { fg = C.orange, style = 'bold' },
  TSDanger = { fg = C.red, style = 'bold' },
  TSTitle = { fg = C.base1, style = 'bold' },
  TSLiteral = { fg = C.green },
  TSURI = { fg = C.blue, style = 'underline' },
  TSMath = { fg = C.base1 },
  TSKeywordOperator = { fg = C.green },
  TSStructure = { fg = C.base1 },
  TSStrong = { fg = C.yellow },
  TSQueryLinterError = { fg = C.orange },
  TSEnvironment = { fg = C.base1 },
  TSEnvironmentName = { fg = C.base1 },
}

return Treesitter
