local palette = require('solarized.palette')
local c = palette.get_colors()

local M = {
  normal = {},
  ellipsis = { fg = c.base0 },
  separator = { link = 'Keyword' },
  modified = { fg = c.warning },
  dirname = { link = 'Directory' },
  basename = { fg = c.base0, bold = true },
  context = { fg = c.base0 },
  context_file = { fg = c.base0 },
  context_module = { link = '@namespace' },
  context_namespace = { link = '@namespace' },
  context_package = { link = 'Directory' },
  context_class = { link = 'Type' },
  context_method = { link = 'Function' },
  context_property = { link = '@field' },
  context_field = { link = '@field' },
  context_constructor = { link = '@constructor' },
  context_enum = { link = 'Type' },
  context_interface = { link = 'Type' },
  context_function = { link = 'Function' },
  context_variable = { link = 'Identifier' },
  context_constant = { link = 'Constant' },
  context_string = { link = 'String' },
  context_number = { link = 'Number' },
  context_boolean = { link = 'Boolean' },
  context_array = { link = 'Delimiter' },
  context_object = { link = '@field' },
  context_key = { link = 'Delimiter' },
  context_null = { link = 'Constant' },
  context_enum_member = { link = 'Constant' },
  context_struct = { link = 'Structure' },
  context_event = { fg = c.base2 },
  context_operator = { link = 'Operator' },
  context_type_parameter = { link = 'Type' },
}

return M
