return function(c)
  local utils = require('solarized.utils')
  local set_hl = utils.set_hl

  set_hl('NotifyBackground', { bg = c.base03 })
  set_hl('NotifyERRORBorder', { fg = c.error })
  set_hl('NotifyWARNBorder', { fg = c.warn })
  set_hl('NotifyINFOBorder', { fg = c.info })
  set_hl('NotifyDEBUGBorder', { fg = c.magenta })
  set_hl('NotifyTRACEBorder', { fg = c.violet })
  set_hl('NotifyERRORIcon', { link = 'NotifyERRORBorder' })
  set_hl('NotifyWARNIcon', { link = 'NotifyWARNBorder' })
  set_hl('NotifyINFOIcon', { link = 'NotifyINFOBorder' })
  set_hl('NotifyDEBUGIcon', { link = 'NotifyDEBUGBorder' })
  set_hl('NotifyTRACEIcon', { link = 'NotifyTRACEBorder' })
  set_hl('NotifyERRORTitle', { link = 'NotifyERRORBorder' })
  set_hl('NotifyWARNTitle', { link = 'NotifyWARNBorder' })
  set_hl('NotifyINFOTitle', { link = 'NotifyINFOBorder' })
  set_hl('NotifyDEBUGTitle', { link = 'NotifyDEBUGTitle' })
  set_hl('NotifyTRACETitle', { link = 'NotifyTRACEBorder' })
  set_hl('NotifyERRORBody', { link = 'Normal' })
  set_hl('NotifyWARNBody', { link = 'Normal' })
  set_hl('NotifyINFOBody', { link = 'Normal' })
  set_hl('NotifyDEBUGBody', { link = 'Normal' })
  set_hl('NotifyTRACEBody', { link = 'Normal' })
end
